[package]
name = "marble"
version = "0.1.0"
edition = "2024"

[lib]
name = "marble"

[workspace]
resolver = "2"
members = ["marble-wasm", "imarble", "marble-language-server"]

[dependencies]
line-index = "0.1.2"
rust-embed = "8.6.0"
