name: Rust

on:
  push:
    branches: [ "main" ]
    paths: [ "src/**", "marble-editor/**", "marble-wasm/**", ".github/workflows/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "src/**", "marble-editor/**", "marble-wasm/**", ".github/workflows/**" ]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Editor
      working-directory: ./marble-wasm
      run: ./build.sh
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./marble-editor

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy Editor
    steps:
      - name: Deploy Editor to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4